<template>
  <div class="input-group" style="min-width: 280px;" v-click-outside="hide">
    <div class="input-group__addon" data-flex="center">
      <svg class="ixo">
        <use xlink:href="#search" />
      </svg>
    </div>
    <input
      type="text"
      class="input"
      @focus="searchActive = true"
      v-model="query"
      placeholder="search documentation.."
    />
    <div class="input-group__addon" data-flex="center" @click="toggle">
      <svg class="ixo" v-show="!searchActive">
        <use xlink:href="#expand-horizontal" />
      </svg>
      <svg class="ixo" v-show="searchActive">
        <use xlink:href="#shrink-horizontal" />
      </svg>
    </div>
    <div class="xui-select-options is-padding-middle-2" v-if="searchActive">
      <router-link
        v-for="(element, index) in filtered(elements)"
        :key="index"
        :to="element.link"
        class="is-ink is-kilo is-padding-middle-2 is-padding-center-3"
        data-flex="center-items"
      >
        <span>{{element.name}}</span>
        <div class="flex-space"></div>
        <div class="tag tag_small is-ink" v-text="element.type"></div>
      </router-link>
    </div>
  </div>
</template>

<script>
import Ixo from './Ixo.vue';
import ClickOutside from 'vue-click-outside';

export default {
  name: 'Searchbar',
  directives: {
    ClickOutside,
  },
  components: {
    Ixo,
  },
  data: () => {
    return {
      searchActive: false,
      currentItem: 1,
      query: '',
      elements: [
        {
          name: 'headings',
          aliases: [
            'is-h1',
            'is-h2',
            'is-h3',
            'is-h4',
            'is-h5',
            'is-h6',
            'is-mega',
            'is-kilo',
            'is-giga',
            'typo',
            'type',
            'atoms',
          ],
          variables: [
            '$base-font-size',
            '$base-line-height',
            '$headings-font-family',
            '$headings-line-height',
            '$headings-weight',
            '$headings-style',
            '$headings-inline-small-style',
            '$h1-style',
            '$h2-style',
            '$h3-style',
            '$h4-style',
            '$h5-style',
            '$h6-style',
            '$giga-style',
            '$mega-style',
            '$kilo-style',
            '$_headings-vertical-rhythm',
            '$headings-spacing-unit',
            '$h1-spacing',
            '$h2-spacing',
            '$h3-spacing',
            '$h4-spacing',
            '$h5-spacing',
            '$h6-spacing',
            '$giga-spacing',
            '$mega-spacing',
            '$kilo-spacing',
          ],
          link: 'headings',
          type: 'atom',
        },
        {
          name: 'paragraphs',
          aliases: ['is-lead', 'p', 'type', 'atoms'],
          variables: [
            '$body-color',
            '$body-font-family',
            '$base-font-size',
            '$base-line-height',
            '$_base-vertical-rhythm',
            '$paragraph-weight',
            '$paragraph-line-height',
            '$paragraph-style',
            '$paragraph-spacing',
            '$paragraph-spacing-unit',
            '$is-lead-weight',
            '$is-lead-line-height',
            '$is-lead-style',
            '$is-lead-spacing',
            '$is-lead-spacing-unit',
          ],
          link: 'paragraphs',
          type: 'atom',
        },
        {
          name: 'lists',
          aliases: ['is-unstyled', 'is-inline', 'ul', 'ol', 'type', 'atoms'],
          link: 'lists',
          type: 'atom',
        },
        {
          name: 'align',
          aliases: ['align-left', 'align-center', 'align-right', 'type', 'modifier'],
          link: 'utils',
          type: 'modifier',
        },
        {
          name: 'font-weight',
          aliases: ['is-light', 'is-normal', 'is-medium', 'is-bold', 'type', 'modifier'],
          link: 'utils',
          type: 'modifier',
          variables: ['$is-light', '$is-normal', '$is-medium', '$is-bold'],
        },
        {
          name: 'font-family',
          aliases: ['is-body-font', 'is-headings-font', 'is-monospace-font', 'type', 'modifier'],
          link: 'utils',
          type: 'modifier',
          variables: ['$body-font-family', '$headings-font-family', '$monospace-font'],
        },
        {
          name: 'text-transform',
          aliases: ['is-uppercase', 'is-lowercase', 'type', 'modifier'],
          link: 'utils',
          type: 'modifier',
        },
        {
          name: 'word-wrap',
          aliases: ['is-nowrap', 'is-ellipsis', 'is-hyphen', 'is-hyphen-block', 'type', 'modifier'],
          link: 'utils',
          type: 'modifier',
        },
        {
          name: 'mark',
          aliases: ['type', 'atoms'],
          link: 'utils',
          type: 'atom',
          variables: ['$mark-color', '$mark-background', '$mark-style'],
        },
        {
          name: 'img-crop',
          aliases: [
            'img-crop-1-1',
            'img-crop-3-4',
            'img-crop-4-3',
            'img-crop-16-9',
            'img-crop-golden',
            'img-crop-silver',
            'img-crop-ultrawide',
            'image',
            'media',
            'atoms',
          ],
          link: 'img-crop',
          type: 'atom',
          variables: ['$img-crop-ratio'],
        },
        {
          name: 'is-outset',
          aliases: ['is-outset_left', 'is-outset_full', 'is-outset_right', 'image', 'media', 'modifier'],
          link: 'img-crop',
          type: 'modifier',
          variables: ['$is-outset', '$is-outset-spacing', '$is-outset-gutter', '$is-outset-bp'],
        },
        {
          name: 'avatar',
          aliases: ['avatar_small', 'avatar_big', 'avatar_square', 'image', 'media', 'atoms'],
          link: 'avatar',
          type: 'atom',
          variables: [
            '$avatar-size',
            '$avatar-small-size',
            '$avatar-big-size',
            '$avatar-border',
            '$avatar-background',
            '$avatar-square-radius',
            '$avatar-style',
          ],
        },
        {
          name: 'img-responsive',
          aliases: ['image', 'media', 'atoms'],
          link: 'img-utils',
          type: 'atom',
        },
        {
          name: 'img-fullwidth',
          aliases: ['image', 'media', 'atoms'],
          link: 'img-utils',
          type: 'atom',
        },
        {
          name: 'fieldset',
          aliases: ['form', 'atoms'],
          link: 'fieldset',
          type: 'atom',
          variables: [
            '$fieldset-spacing',
            '$fieldset-padding',
            '$ieldset-background',
            '$fieldset-border',
            '$fieldset-style',
          ],
        },
        {
          name: 'field-group',
          aliases: ['form', 'input', 'field-group_boolean', 'field-group__label', 'field-group__info', 'molecules'],
          link: 'field-group',
          type: 'molecules',
          variables: [
            '$field-group-spacing',
            '$field-group-padding',
            '$field-group-background',
            '$field-group-style',
            '$field-group-label-spacing',
            '$field-group-label-font-size',
            '$field-group-label-style',
            '$field-group-info-spacing',
            '$field-group-info-font-size',
            '$field-group-info-style',
          ],
        },
        {
          name: 'input',
          aliases: ['form', 'input', 'input_small', 'input_big', 'input_round', 'atoms'],
          link: 'input',
          type: 'atom',
          variables: [
            '$input-padding-ratio',
            '$input-spacing',
            '$input-border-color',
            '$input-border-width',
            '$input-border-style',
            '$input-background',
            '$input-color',
            '$input-round',
            '$input-radius',
            '$input-hover-style',
            '$input-focus-style',
            '$input-disabled-style',
            '$input-placeholder-color',
            '$input-placeholder-style',
            '$input-placeholder-hover-style',
            '$input-placeholder-focus-style',
            '$input-font-size',
            '$input-line-height',
            '$input-min-height',
            '$input-style',
            '$input-small-font-size',
            '$input-small-line-height',
            '$input-small-min-height',
            '$input-small-style',
            '$input-big-font-size',
            '$input-big-line-height',
            '$input-big-min-height',
            '$input-big-style',
          ],
        },
        {
          name: 'input-group',
          aliases: ['form', 'input-group__addon', 'input-group__addon', 'input_round', 'atoms'],
          link: 'input-group',
          type: 'atom',
          variables: [
            '$input-group-spacing',
            '$input-group-addon-color',
            '$input-group-addon-background',
            '$input-group-addon-border-color',
            '$input-group-addon-border-width',
            '$input-group-addon-border-style',
            '$input-group-addon-padding',
            '$input-group-addon-style',
          ],
        },
        {
          name: 'xui-checkbox',
          aliases: ['form', 'xui-checkbox__label', 'atoms'],
          link: 'xui-checkbox',
          type: 'atom',
          variables: [
            '$xui-checkbox-spacing',
            '$xui-checkbox-height',
            '$xui-checkbox-radius',
            '$xui-checkbox-background',
            '$xui-checkbox-style',
            '$xui-checkbox-hover-style',
            '$xui-checkbox-checked-style',
            '$xui-checkbox-check-size',
            '$xui-checkbox-check-color',
            '$xui-checkbox-check-hover-color',
            '$xui-checkbox-check-checked-color',
          ],
        },
        {
          name: 'xui-radio',
          aliases: ['form', 'xui-radio__label', 'atoms'],
          link: 'xui-radio',
          type: 'atom',
          variables: [
            '$xui-radio-spacing',
            '$xui-radio-height',
            '$xui-radio-background',
            '$xui-radio-style',
            '$xui-radio-hover-style',
            '$xui-radio-checked-style',
            '$xui-radio-dot-size',
            '$xui-radio-dot-color',
            '$xui-radio-dot-hover-color',
            '$xui-radio-dot-checked-color',
          ],
        },
        {
          name: 'xui-toggle',
          aliases: ['form', 'xui-toggle__label', 'xui-toggle__switch', 'atoms'],
          link: 'xui-toggle',
          type: 'atom',
        },
        {
          name: 'xui-select',
          aliases: [
            'form',
            'xui-select__selected',
            'xui-select__placeholder',
            'xui-select__caret',
            'xui-select-options',
            'atoms',
          ],
          link: 'xui-select',
          type: 'atom',
        },
        {
          name: 'range-slider',
          aliases: ['form', 'atoms'],
          link: 'range-slider',
          type: 'atom',
        },
        {
          name: 'file-upload',
          aliases: ['form', 'file-upload__input', 'atoms'],
          link: 'file-upload',
          type: 'atom',
        },
        {
          name: 'button',
          aliases: [
            'form',
            'interaction',
            'btn',
            'submit',
            'btn_minor',
            'btn_super',
            'btn_invert',
            'btn_clear',
            'btn_small',
            'btn_big',
            'btn_wide',
            'btn_block',
            'btn_round',
            'btn_outlined',
            'btn_square',
            'atoms',
          ],
          link: 'button',
          type: 'atom',
        },
        {
          name: 'button-group',
          aliases: [
            'form',
            'interaction',
            'btn',
            'submit',
            'btn-group__start',
            'btn-group__inner',
            'btn-group__divider',
            'btn-group__end',
            'molecules',
          ],
          link: 'button-group',
          type: 'molecule',
        },
        {
          name: 'hamburger',
          aliases: ['form', 'interaction', 'sidebar', 'navbar', 'btn', 'menu', 'atoms'],
          link: 'hamburger',
          type: 'atom',
        },
        {
          name: 'nav',
          aliases: [
            'form',
            'interaction',
            'sidebar',
            'navbar',
            'btn',
            'menu',
            'menubar',
            'nav__item',
            'nav__divider',
            'molecules',
          ],
          link: 'nav',
          type: 'molecule',
        },
        {
          name: 'dropdown',
          aliases: [
            'form',
            'interaction',
            'dropdown-options',
            'btn',
            'menu',
            'dropdown_divider',
            'dropdown_above',
            'on-hover',
            'dropdown_left',
            'dropdown_center',
            'dropdown_right',
            'dropdown_full',
            'molecules',
          ],
          link: 'dropdown',
          type: 'molecule',
        },
        {
          name: 'tag',
          aliases: [
            'form',
            'interaction',
            'label',
            'tag_minor',
            'tag_link',
            'tag_super',
            'tag_highlight',
            'tag_info',
            'tag_error',
            'tag_success',
            'tag_warning',
            'tag_small',
            'tag_big',
            'tag_round',
            'tag_outlined',
            'atoms',
          ],
          link: 'tag',
          type: 'atom',
        },
        {
          name: 'meatball',
          aliases: ['form', 'button', 'feedback', 'label', 'tag', 'atoms'],
          link: 'meatball',
          type: 'atom',
        },
        {
          name: 'loader',
          aliases: ['form', 'feedback', 'interaction', 'is-local', 'is-global', 'atoms'],
          link: 'loader',
          type: 'atom',
        },
        {
          name: 'alert',
          aliases: [
            'form',
            'feedback',
            'interaction',
            'alert_small',
            'alert_big',
            'alert_info',
            'alert_error',
            'alert_success',
            'alert_warning',
            'molecules',
          ],
          link: 'alert',
          type: 'molecule',
        },
        {
          name: 'data-tooltip',
          aliases: [
            'form',
            'feedback',
            'interaction',
            'data-tooltip-top',
            'data-tooltip-right',
            'data-tooltip-bottom',
            'data-tooltip-left',
            'modifier',
          ],
          link: 'data-tooltip',
          type: 'modifier',
        },
        {
          name: 'titlebar',
          aliases: ['form', 'toolbar', 'interface', 'ui', 'organisms'],
          link: 'titlebar',
          type: 'organism',
        },
        {
          name: 'xui-list',
          aliases: [
            'form',
            'interface',
            'ui',
            'xui-list-group',
            'xui-list-group-header',
            'xui-list-item',
            'xui-list-item__start',
            'xui-list-item__label',
            'xui-list-item__end',
            'organisms',
          ],
          link: 'xui-list',
          type: 'organism',
        },
        {
          name: 'xui-accordion',
          aliases: [
            'form',
            'interface',
            'ui',
            'xui-accordion__handle',
            'xui-accordion__target',
            'is-visible-collapsed',
            'is-hidden-collapsed',
            'molecules',
          ],
          link: 'xui-accordion',
          type: 'molecule',
        },
        {
          name: 'modal',
          aliases: [
            'interface',
            'ui',
            'modal_deck',
            'opens-right',
            'modal_toast',
            'opens-bottom',
            'modal_overlay',
            'modal-wrapper',
            'modal__header',
            'modal__dismiss',
            'modal__body',
            'modal__footer',
            'molecules',
          ],
          link: 'modal',
          type: 'molecule',
        },
        {
          name: 'card',
          aliases: ['interface', 'ui', 'molecules'],
          link: 'card',
          type: 'molecule',
        },
        {
          name: 'well',
          aliases: ['interface', 'feedback', 'ui', 'molecules'],
          link: 'well',
          type: 'molecule',
        },
        {
          name: 'table',
          aliases: ['interface', 'data', 'table_bordered', 'table_clear', 'ui', 'molecules'],
          link: 'table',
          type: 'molecule',
        },
        {
          name: 'is-ink',
          aliases: [
            'styling',
            'interface',
            'is-ink-light',
            'is-ink-lighter',
            'is-ink-lightest',
            'is-ink-link',
            'is-ink-super',
            'is-ink-highlight',
            'is-ink-invert',
            'hover:is-ink-light',
            'hover:is-ink-lighter',
            'hover:is-ink-lightest',
            'hover:is-ink-link',
            'hover:is-ink-super',
            'hover:is-ink-highlight',
            'hover:is-ink-invert',
            'ui',
            'modifier',
          ],
          link: 'is-ink',
          type: 'modifier',
        },
        {
          name: 'is-theme',
          aliases: [
            'styling',
            'interface',
            'is-theme-lightest',
            'is-theme-invert',
            'hover:is-theme',
            'hover:is-theme-lightest',
            'hover:is-theme-invert',
            'ui',
            'modifier',
          ],
          link: 'is-theme',
          type: 'modifier',
        },
        {
          name: 'is-elevated',
          aliases: ['styling', 'interface', 'hover:is-elevated', 'ui', 'modifier'],
          link: 'is-elevated',
          type: 'modifier',
        },
        {
          name: 'is-radius',
          aliases: [
            'styling',
            'interface',
            'is-radius-top',
            'is-radius-tr',
            'is-radius-right',
            'is-radius-br',
            'is-radius-bottom',
            'is-radius-bl',
            'is-radius-left',
            'is-radius-tl',
            'is-radius-0-top',
            'is-radius-0-tr',
            'is-radius-0-right',
            'is-radius-0-br',
            'is-radius-0-bottom',
            'is-radius-0-bl',
            'is-radius-0-left',
            'is-radius-0-tl',
            'is-radius-0',
            'is-round',
            'is-round-top',
            'is-round-tr',
            'is-round-right',
            'is-round-br',
            'is-round-bottom',
            'is-round-bl',
            'is-round-left',
            'is-round-tl',
            'ui',
            'modifier',
          ],
          link: 'is-radius',
          type: 'modifier',
        },
        {
          name: 'is-border',
          aliases: [
            'styling',
            'interface',
            'ui',
            'is-border-top',
            'is-border-right',
            'is-border-bottom',
            'is-border-left',
            'is-border-middle',
            'is-border-center',
            'modifier',
          ],
          link: 'is-border',
          type: 'modifier',
        },
        {
          name: 'data-grid',
          aliases: ['layout', 'interface', 'ui', 'small-gutter', 'no-gutter', 'start', 'center', 'end'],
          link: 'grid',
          type: 'layout',
        },
        {
          name: 'data-container',
          aliases: ['layout', 'interface', 'ui', 'data-grid'],
          link: 'grid',
          type: 'layout',
        },
        {
          name: 'data-col',
          aliases: ['layout', 'interface', 'ui', 'data-grid', 'fit', 'auto'],
          link: 'grid',
          type: 'layout',
        },
        {
          name: 'data-flex',
          aliases: [
            'layout',
            'interface',
            'ui',
            'justify-content',
            'align-items',
            'flex-direction',
            'flex-wrap',
            'align-content',
          ],
          link: 'data-flex',
          type: 'layout',
        },
        {
          name: 'bumper',
          aliases: ['layout', 'interface', 'ui', 'bumper_invert', 'bumper_small', 'bumper_big', 'spacer', 'atoms'],
          link: 'spacer',
          type: 'atom',
        },
        {
          name: 'divider',
          aliases: ['layout', 'interface', 'ui', 'divider_invert', 'divider_small', 'divider_big', 'spacer', 'atoms'],
          link: 'spacer',
          type: 'atom',
        },
        {
          name: 'spacer',
          aliases: ['layout', 'interface', 'ui', 'spacer_small', 'spacer_big', 'atoms'],
          link: 'spacer',
          type: 'atom',
        },
        {
          name: 'x-space',
          aliases: ['layout', 'interface', 'ui', 'atoms'],
          link: 'spacer',
          type: 'atom',
        },
        {
          name: 'y-space',
          aliases: ['layout', 'interface', 'ui', 'atoms'],
          link: 'spacer',
          type: 'atom',
        },
        {
          name: 'flex-space',
          aliases: ['layout', 'interface', 'ui', 'atoms'],
          link: 'spacer',
          type: 'atom',
        },
        {
          name: 'is-margin',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'is-margin-top',
            'is-margin-right',
            'is-margin-bottom',
            'is-margin-left',
            'is-margin-middle',
            'is-margin-center',
          ],
          link: 'is-margin',
          type: 'modifier',
        },
        {
          name: 'is-padding',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'is-padding-top',
            'is-padding-right',
            'is-padding-bottom',
            'is-padding-left',
            'is-padding-middle',
            'is-padding-center',
          ],
          link: 'is-padding',
          type: 'modifier',
        },
        {
          name: 'is-height',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'is-height-16-9',
            'is-height-full',
            'is-height-1-4',
            'is-height-half',
            'is-height-3-4',
            'is-height-golden',
            'is-height-vw-16-9',
            'is-height-vw-full',
            'is-height-vw-1-4',
            'is-height-vw-half',
            'is-height-vw-3-4',
            'is-height-vw-golden',
            'is-height-vh-16-9',
            'is-height-vh-full',
            'is-height-vh-1-4',
            'is-height-vh-half',
            'is-height-vh-3-4',
            'is-height-vh-golden',
          ],
          link: 'is-height',
          type: 'modifier',
        },
        {
          name: 'is-min-height',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'is-min-height-16-9',
            'is-min-height-full',
            'is-min-height-1-4',
            'is-min-height-half',
            'is-min-height-3-4',
            'is-min-height-golden',
            'is-min-height-vw-16-9',
            'is-min-height-vw-full',
            'is-min-height-vw-1-4',
            'is-min-height-vw-half',
            'is-min-height-vw-3-4',
            'is-min-height-vw-golden',
            'is-min-height-vh-16-9',
            'is-min-height-vh-full',
            'is-min-height-vh-1-4',
            'is-min-height-vh-half',
            'is-min-height-vh-3-4',
            'is-min-height-vh-golden',
          ],
          link: 'is-height',
          type: 'modifier',
        },
        {
          name: 'is-width',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'is-width-16-9',
            'is-width-full',
            'is-width-1-4',
            'is-width-half',
            'is-width-3-4',
            'is-width-golden',
            'is-width-vw-16-9',
            'is-width-vw-full',
            'is-width-vw-1-4',
            'is-width-vw-half',
            'is-width-vw-3-4',
            'is-width-vw-golden',
            'is-width-vh-16-9',
            'is-width-vh-full',
            'is-width-vh-1-4',
            'is-width-vh-half',
            'is-width-vh-3-4',
            'is-width-vh-golden',
          ],
          link: 'is-width',
          type: 'modifier',
        },
        {
          name: 'is-min-width',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'is-min-width-16-9',
            'is-min-width-full',
            'is-min-width-1-4',
            'is-min-width-half',
            'is-min-width-3-4',
            'is-min-width-golden',
            'is-min-width-vw-16-9',
            'is-min-width-vw-full',
            'is-min-width-vw-1-4',
            'is-min-width-vw-half',
            'is-min-width-vw-3-4',
            'is-min-width-vw-golden',
            'is-min-width-vh-16-9',
            'is-min-width-vh-full',
            'is-min-width-vh-1-4',
            'is-min-width-vh-half',
            'is-min-width-vh-3-4',
            'is-min-width-vh-golden',
          ],
          link: 'is-width',
          type: 'modifier',
        },
        {
          name: 'is-absolute',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'position'],
          link: 'position',
          type: 'modifier',
        },
        {
          name: 'is-relative',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'position'],
          link: 'position',
          type: 'modifier',
        },
        {
          name: 'is-fixed',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'position'],
          link: 'position',
          type: 'modifier',
        },
        {
          name: 'is-sticky',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'position'],
          link: 'position',
          type: 'modifier',
        },
        {
          name: 'is-placed',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'position',
            'is-placed-n',
            'is-placed-ne',
            'is-placed-e',
            'is-placed-se',
            'is-placed-s',
            'is-placed-sw',
            'is-placed-w',
            'is-placed-nw',
            'is-placed-0',
          ],
          link: 'position',
          type: 'modifier',
        },
        {
          name: 'is-layer',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'position',
            'is-layer-1',
            'is-layer-10',
            'is-layer-100',
            'is-layer-9999',
            'z-index',
          ],
          link: 'position',
          type: 'modifier',
        },
        {
          name: 'is-block',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'display'],
          link: 'display',
          type: 'modifier',
        },
        {
          name: 'is-hidden',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'display'],
          link: 'display',
          type: 'modifier',
        },
        {
          name: 'is-flex',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'display'],
          link: 'display',
          type: 'modifier',
        },
        {
          name: 'is-scrollable',
          aliases: [
            'layout',
            'interface',
            'ui',
            'modifier',
            'overflow',
            'is-scrollable-y-contain',
            'is-scrollable-x-contain',
            'is-scrollable-contain',
            'is-scrollable-auto-contain',
            'is-scrollable-auto-x-contain',
            'is-scrollable-auto-y-contain',
          ],
          link: 'overflow',
          type: 'modifier',
        },
        {
          name: 'is-clipped',
          aliases: ['layout', 'interface', 'ui', 'modifier', 'overflow'],
          link: 'overflow',
          type: 'modifier',
        },
        {
          name: 'clearfix',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'elevation',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'ellipsis',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'get-font-size',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'headings',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'inject-style',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'is-scrollable',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'metrics',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'placeholder',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'set-breakpoints',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'set-data-breakpoints',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'set-data-map-breakpoints',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'set-theme-colors',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'word-wrap',
          aliases: ['mixins'],
          link: 'mixins',
          type: 'mixin',
        },
        {
          name: 'array-magic',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'bp',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'brightness-difference',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'check-compliance',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'color-difference',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'color-margin',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'color-pass',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'contrast-ratio',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'em',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'find-contrast-loop',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'flatten-color',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'get-brightness',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'get-color',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'get-space',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'luma',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'next-bp',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'pow',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'rem',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'set-contrast',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'set-hover',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'shade-by-contrast',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'strip-unit',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'system-color',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: 'var-color',
          aliases: ['functions'],
          link: 'functions',
          type: 'function',
        },
        {
          name: '$_flatten-color-base',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$_luma-text',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$_set-hover-shading',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$_system-color-ref',
          aliases: ['variables'],
          link: 'variables',
        },
        {
          name: '$base-font-size',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$base-scale-unit',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$base-spacing',
          aliases: ['variables'],
          link: 'variables',
        },
        {
          name: '$base-spacing-unit',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$breakpoints',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$color-map-id',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$darker-fallback',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$elevation-color',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$elevation-opacity',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$lighter-fallback',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$root-size',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$spacings',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$type-scale',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$type-scale-bp',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$type-scale-unit',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
        {
          name: '$xui-colors',
          aliases: ['variables'],
          link: 'variables',
          type: 'variable',
        },
      ],
    };
  },
  methods: {
    hide() {
      this.searchActive = false;
    },
    toggle() {
      this.searchActive = !this.searchActive;
    },
    filtered(elements) {
      const { query } = this;
      const filtered = elements.filter((element) => {
        const regex = new RegExp(`(${query})`, 'i');
        return (
          (element.aliases && element.aliases.some((t) => t.match(regex))) ||
          element.name.match(regex) ||
          (element.variables && element.variables.some((v) => v.match(regex)))
        );
      });
      return filtered;
    },

    looseFocus() {
      setTimeout(() => (this.showPopdown = false), 200);
    },
  },
};
</script>

<style scoped lang="scss">
</style>
